default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kapitol_reef_store_development
test:
  <<: *default
  database: kapitol_reef_store_test

production:
  <<: *default
  database: kapitol_reef__store_production
  username: kapitol_reef_store
  password: <%= ENV['KAPITOL_STORE_DATABASE_PASSWORD'] %>
